apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "coordinator.fullname" . }}
  labels:
    app: {{ template "coordinator.name" . }}
    chart: {{ template "coordinator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "coordinator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "coordinator.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config-common: {{ .Values.global.druid | toYaml | sha256sum }}
        checksum/config: {{ .Values.druid | toYaml | sha256sum }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-common
          configMap:
            name: {{ .Release.Name }}-common
            # Required for a temporary workaround with name resolution
            # we insert "druid.host" in entrypoint script
            defaultMode: 0666
        - name: {{ template "coordinator.fullname" . }}
          configMap:
            name: {{ template "coordinator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRUID_ROLE
              value: {{ template "coordinator.name" . }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.druid.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          volumeMounts:
            - mountPath: /opt/druid/conf-k8s/_common/
              name: {{ .Release.Name }}-common
            - mountPath: /opt/druid/conf-k8s/coordinator/
              name: {{ template "coordinator.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
