---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monitoring.fullname" . }}
  labels:
    app: {{ template "monitoring.name" . }}
    chart: {{ template "monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "files/*").AsConfig .) | indent 2 }}
