apiVersion: v1
kind: Service
metadata:
  name: {{ template "monitoring.fullname" . }}
  labels:
    app: {{ template "monitoring.name" . }}
    chart: {{ template "monitoring.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: http
    - port: 9125
      targetPort: statsd-udp
      protocol: UDP
      name: statsd-udp
    - port: 9125
      targetPort: statsd-tcp
      protocol: TCP
      name: statsd-tcp
  selector:
    app: {{ template "monitoring.name" . }}
    release: {{ .Release.Name }}
