apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "broker.fullname" . }}
  labels:
    app: {{ template "broker.name" . }}
    chart: {{ template "broker.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "broker.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "broker.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config-common: {{ .Values.global.druid | toYaml | sha256sum }}
        checksum/config: {{ .Values.druid | toYaml | sha256sum }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-common
          configMap:
            name: {{ .Release.Name }}-common
        - name: {{ template "broker.fullname" . }}
          configMap:
            name: {{ template "broker.fullname" . }}
{{ include "monitoring.volumes" . | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DRUID_ROLE
              value: {{ template "broker.name" . }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.druid.port }}
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "wget -qO - http://$MY_POD_IP:{{.Values.druid.port}}/druid/broker/v1/loadstatus | grep -q '{\"inventoryInitialized\":true}'"
          readinessProbe:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "wget -qO - http://$MY_POD_IP:{{.Values.druid.port}}/druid/broker/v1/loadstatus | grep -q '{\"inventoryInitialized\":true}'"
          volumeMounts:
            - mountPath: /opt/druid/conf-k8s/_common/
              name: {{ .Release.Name }}-common
            - mountPath: /opt/druid/conf-k8s/broker/
              name: {{ template "broker.fullname" . }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{ include "monitoring.containers" . | indent 8 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
